gslt: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
stv_password: "your_stv_password"
srcds_rcon_password: "your_rcon_password"
srcds_server_password: "your_server_password"
ip: "12.34.56.78"
database:
  sourcebans:
    user: sourcebans
    pass: change_me
  smadmins:
    user: smadmins
    pass: change_me
  clientprefs:
    user: clientprefs
    pass: change_me
  storage_local:
    user: storagelocal
    pass: change_me

discord:
  stac_webhook: "https://discord.com/api/webhooks/1111111111111111111/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  crash_webhook: "https://discord.com/api/webhooks/22222222222222222222/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
