---

- name: Create /srv/webroot directory
  ansible.builtin.file:
    path: /srv/webroot
    owner: www-data
    group: www-data
    state: directory
    mode: "0770"

- name: /srv/webroot/index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "/srv/webroot/index.html"
    owner: www-data
    group: www-data
    mode: 0755

- name: Check if stats installed
  ansible.builtin.stat:
    path: "/srv/stats"
  register: stats_exists

- name: Install hlstatx-ce
  import_tasks: stats.yml

- name: Check if sourcebans installed
  ansible.builtin.command: ls /srv/sourcebans/sourcebans-pp-1.7.0.webpanel-only/index.php
  register: sourcebans_exists

- name: Install sourcebans
  import_tasks: sourcebans.yml
  #when: not sourcebans_exists
