---
- name: Create srcds directory
  ansible.builtin.file:
    path: ~/srcds
    state: directory
    mode: "0755"

- name: Update TF2
  ansible.builtin.command: dotnet ~/dd/DepotDownloader.dll -app 232250 -os linux -osarch 32 -max-downloads 8 -dir ~/srcds

- name: Copy sourcemod distribution to /tf
  ansible.posix.synchronize:
    src: /home/tf2server/sourcemod/
    dest: /home/tf2server/srcds/tf/
    recursive: true
  # Perform the copy from the *remote* sourcemod build output
  delegate_to: "{{ inventory_hostname }}"

- name: /tf/mapcycle.txt
  ansible.builtin.template:
    src: mapcycle.txt.j2
    dest: ~/srcds/tf/mapcycle.txt
    mode: 0755

- name: /tf/cfg/autoexec.cfg
  ansible.builtin.template:
    src: autoexec.cfg.j2
    dest: ~/srcds/tf/cfg/autoexec.cfg
    mode: 0755

- name: /tf/cfg/server.cfg
  ansible.builtin.template:
    src: server.cfg.j2
    dest: ~/srcds/tf/cfg/server.cfg
    mode: 0755

- name: /tf/cfg/motd.cfg
  ansible.builtin.template:
    src: motd.txt.j2
    dest: ~/srcds/tf/cfg/motd.txt
    mode: 0755

- name: Generate /entry.sh
  ansible.builtin.template:
    src: "entry.sh.j2"
    dest: "~/srcds/entry.sh"
    mode: 0775

- name: Generate shell.sh
  ansible.builtin.copy:
    mode: 0775
    content: "tmux -S ./tmux.sock attach"
    dest: "~/srcds/shell.sh"

- name: ufw allow 27015/udp
  become: true
  ansible.builtin.ufw:
    rule: allow
    port: "27015"
    proto: udp

- name: ufw allow 27015/tcp
  become: true
  ansible.builtin.ufw:
    rule: allow
    port: "27015"
    proto: tcp

- name: ufw allow 27016
  become: true
  ansible.builtin.ufw:
    rule: allow
    port: "27016"
    proto: udp

- name: ufw allow 27020
  become: true
  ansible.builtin.ufw:
    rule: allow
    port: "27020"
    proto: udp

- name: /etc/systemd/system/tf2server.service
  become: true
  ansible.builtin.template:
    src: tf2server.service.j2
    dest: "/etc/systemd/system/tf2server.service"
    mode: 0755

- name: Restart tf2server
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: tf2server

- name: cron
  become: true
  ansible.builtin.cron:
    name: "tf2-restart"
    weekday: "*"
    minute: "0"
    hour: "6"
    job: "systemctl restart tf2server"
